version: '4'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development

  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config.db:/etc/mosquitto/mosquitto.db

  shell:
    build: .
    command: /bin/bash